wazuh/wazuh-docker

docker-compose.yml
kibana/config/kibana.yml
kibana/config/wait-for-it.sh

Hi,
This PR adds the ability to configure the Wazuh APP, please review, thanks.
Regards.

Configure Wazuh API

---

docker-compose.yml

Fixes SELinux permission issues on the fly.
Fixes NGINX .htaccess file not beeing persistent and easily editable
This is likely to fix #33

docker-compose fix SELinux and NGINX

---

docker-compose.yml

`wazuh-kibana` image version version is wrong. It should be `3.4.0_6.3.1`

Fix wazuh/wazuh-kibana image version to 3.4.0_6.3.1

---

kibana/Dockerfile

Closes https://github.com/wazuh/wazuh-docker/issues/52

Fix typo in Kibana chown command

---

README.md
docker-compose.yml

Hello team
Fixed the script reference in the readme. 
Best regards,

Fixed script reference

---

nginx/config/entrypoint.sh

Hello team, this PR increases proxy buffer for NGINX Kibana configuration.
Regards

Increased proxy buffer for NGINX Kibana

---

kibana/Dockerfile

This commit fixes the branch name where pull the template from Elastic.

Update branch to apply the template

---

docker-compose.yml
kibana/Dockerfile
logstash/Dockerfile
wazuh/Dockerfile

Hello team,
With this PR we update the version of Elastic Stack to 6.5.4. 
Regards,

Update Elastic Stack version to 6.5.4

---

wazuh/Dockerfile

Hello team, 
This PR solves #83 
Regards,

Temporary fix for Wazuh cluster master node in Kubernetes

---

kibana/Dockerfile
kibana/config/entrypoint.sh
kibana/config/wazuh_app_config.sh

Hello team,
We have added the necessary environment variables to configure the Wazuh APP `config.yml `file for Kibana.
Regards,

Kibana env variables

---

CHANGELOG.md
docker-compose.yml
kibana/Dockerfile
wazuh/Dockerfile

Hello team,
This PR updates Wazuh to version 3.8.1.
Best regards,

Update to Wazuh version 3.8.1

---

CHANGELOG.md
docker-compose.yml
kibana/Dockerfile
wazuh/Dockerfile

Hello team,
This PR updates Wazuh version to 3.8.2.
Best regards,

Update to Wazuh version 3.8.2

---

docker-compose.yml

Hi folks,
This PR removes useless comments and deprecated statements in the `docker-compose.yml` file.
Related issue: #113 
Cheers

Updating docker-compose file

---

LICENSE
README.md
docker-compose.yml
kibana/Dockerfile
kibana/config/entrypoint.sh
kibana/config/wazuh_app_config.sh
logstash/Dockerfile
logstash/config/01-wazuh.conf
logstash/config/run.sh
nginx/Dockerfile
nginx/config/entrypoint.sh
wazuh/Dockerfile
wazuh/config/entrypoint.sh
wazuh/config/filebeat.yml
wazuh/config/init.bash

Hi team,
this PR change to 2019 the year displayed for the copyright.

Changing copyright year to 2019

---

README.md
docker-compose.yml
elasticsearch/Dockerfile
elasticsearch/config/config_cluster.sh
elasticsearch/config/entrypoint.sh
elasticsearch/config/load_settings.sh
kibana/Dockerfile
kibana/config/entrypoint.sh
kibana/config/kibana_settings.sh
kibana/config/wazuh_app_config.sh
logstash/Dockerfile
logstash/config/01-wazuh.conf
logstash/config/entrypoint.sh
nginx/Dockerfile
nginx/config/entrypoint.sh
wazuh/Dockerfile
wazuh/config/00-wazuh.sh
wazuh/config/entrypoint.sh
wazuh/config/filebeat.yml
wazuh/config/init.bash

Hello team,
This PR fixes a typo in the copyright comments in the script and Dockerfiles. Related issue here #172 
Regards

Updated copyright comments

---

elasticsearch/config/load_settings.sh
logstash/config/10-entrypoint.sh

Hello team,
This PR solves #186. We solved the problems we had with Logstash logs. 
Best regards,

Problems with Logstash logs and certificates resolved

---

CHANGELOG.md
README.md
docker-compose.yml
elasticsearch/Dockerfile
elasticsearch/config/30-entrypoint.sh
kibana/Dockerfile
logstash/Dockerfile
wazuh/Dockerfile

Hello team,
This PR upgrade the K8S branch to 3.9.3_6.8.1.
Best regards,

Upgrade to 3.9.3_6.8.1 version

---

wazuh/config/01-wazuh.sh

Hi team!
This PR solves issue https://github.com/wazuh/wazuh-docker/issues/208. Files are removed properly to avoid exiting the script execution.
Best regards,
Mayte Ariza

Fixing remove files function 

---

elasticsearch/Dockerfile
kibana/Dockerfile
logstash/Dockerfile
wazuh/Dockerfile

Hi team!!
This PR adds the followings **upgrades**:
- **Elasticsearch** version 6.8.2
- **Kibana** version 6.8.2
- **Logstash** version 6.8.2
- **Filebeat** version 6.8.2
Best regards,
Mayte Ariza

Update Cloud version from 6.8.1 to 6.8.2

---

elasticsearch/Dockerfile

Hi team,
This PR solves #243 . Thanks @SitoRBJ for reporting this unexpected behavior.
Regards

Fixed S3 plugin

---

kibana/Dockerfile

Hello team,
This PR solves permissions problems with Wazuh APP in Kibana. 
Regards,

Cloud 0.7 app installation fix

---

kibana/Dockerfile

Add app 3.10.2 - 7.3.2 with this fix https://github.com/wazuh/wazuh-kibana-app/issues/1815

App 3.10.2 - 7.3.2 with security fix

---

wazuh/config/filebeat.yml

Hello team,
This PR solves #266. Now the `filebeat.yml` configuration file was updated to the latest version.
Cheers

Updated Filebeat configuration file

---

logstash/config/01-wazuh.conf

Hello team,
We bring the pipeline solution to the cloud branch-0.9
Best regards,

Wazuh pipeline vulnerability detector workaround

---

kibana/Dockerfile
kibana/config/12-custom_logos.sh

Hello team,
This PR offers the option of filling out a script to change the Kibana logos.
Best regards,

Add custom logos for kibana script

---

kibana/config/welcome_wazuh.sh

Hello team,
This PR hides the index management option in Kibana.
Best regards,

Hide index management option in Kibana

---

nginx/config/entrypoint.sh

This PR fixes https://github.com/wazuh/wazuh-docker/issues/301
Updating nginx config format to avoid deprecation warning.

Update Nginx config syntax

---

nginx/Dockerfile
nginx/config/entrypoint.sh

Fix 302 Execute nginx as PID 1

---

kibana/Dockerfile

Hello team,
This PR add custom app .11.5_7.4.2 for cloud 0.22
Best regards

Add custom app 3.11.5_7.4.2 for cloud 0.22

---

wazuh/Dockerfile

Hello team,
This PR adapts code to Wazuh 3.12.2 and Filebeat to 7.6.1
Best regards

Adapt cloud to 3.12.2_7.6.1

---

wazuh/config/permanent_data.env

Hello team,
This PR solves the issue with the file:
New file: /var/ossec/queue/fim/db/fim.db. It is not persistent.
Best regards

Add fim.db to be removed in updates

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud branch to use Wazuh 3.12.3
Regards

Adapt cloud branch to Wazuh 3.12.3

---

wazuh/Dockerfile

This PR updates S6-overlay init system to its latest version

Bump S6-overlay version

---

kibana/config/kibana_settings.sh

This PR fixes #355 
Adds HTTP credentials to curl check when required

Add HTTP auth to curl when required

---

wazuh/Dockerfile

Hello team,
This PR updates Wazuh version to 3.13.0
Best regards

update Wazuh version to 3.13.0

---

nginx/config/entrypoint.sh

This PR fixes #366 and superseeds #365

Bugfix port 80 redirects

---

wazuh/Dockerfile

Hello team,
This PR update Wazuh server version to 3.13.2
Regards

Update Wazuh version to 3.13.2

---

wazuh/Dockerfile
wazuh/config/filebeat.runit.service
wazuh/config/postfix.runit.service
wazuh/config/wazuh-api.runit.service
wazuh/config/wazuh.runit.service

Hello team,
This issue update the Wazuh image to use CentOS base image
Thank you.
Regards,
Jose.

Centos7 wazuh

---

wazuh-odfe/config/create_user.py

This PR fixes #402 
- Only default unused users, leaving the possibility to define new users from Kibana UI and respect these passwords.
- The disable user logic was refactored into a separate function.

Fix password change and refactor disable user into function

---

wazuh/Dockerfile

Hello team,
This PR update wazuh version to 4.0.3
Regards

Update wazuh version to 4.0.3

---

wazuh/Dockerfile

Hello team,
This PR update the Wazuh version to 4.0.3 and adds a new configuration that allows blocking the upload of files with remote commands.
Regards,
Mayte Ariza

Update wazuh version to 4.0.3 + block remote commands

---

.github/workflows/push.yml
.goss.kibana.yaml
.goss.yaml

This PR closes #423 
- Implement Goss validations on Actions

Implement image validation

---

wazuh/Dockerfile

Hello team,
This PR updates Filebeat version to 7.10.0 for Open Distro 1.12.0
Regards

Update filebeat to 7.10.0

---

wazuh/Dockerfile
wazuh/config/01-wazuh.sh

Hello team,
This PR update Wazuh version
Regards

Adap to wazuh 4.1.2

---

wazuh/Dockerfile

Hello team,
This PR updates Wazuh to 4.1.4

Update Wazuh to v4.1.4

---

wazuh/Dockerfile

Hello team,
This PR updates Filebeat version to 7.10.2
Regards

Update Filebeat to v7.10.2

---

wazuh/Dockerfile

Hello team,
This PR updates Wazuh docker version to 4.1.5
Regards

Update to Wazuh v4.1.5

---

.goss.yaml

Agent process unification

---

.goss.yaml
production-cluster.yml
wazuh-odfe/config/etc/cont-init.d/0-wazuh-init
wazuh-odfe/config/etc/cont-init.d/2-manager

Rename manager ossec.conf to manager.conf

---

CHANGELOG.md
wazuh-odfe/config/etc/services.d/ossec-logs/run

Rename ossec.log to wazuh.log

---

wazuh/config/permanent_data.env

Hello team,
This PR fixes wodel AWS dependencies error.

Add utils.py to files mounted that should not be permanent

---

wazuh-odfe/config/permanent_data.env

This PR solved the error presented in the Issue https://github.com/wazuh/wazuh-docker/issues/507

Add /var/ossec/logs/archives to permanent_data

---

wazuh-odfe/config/permanent_data.env

Fixed errors generated with directories nested within PERMANENT_DATA

Fix directory problem in permanent_data

---

wazuh/Dockerfile

This PR adaptas Wazuh cloud image to v4.2.4

Update Wazuh version to v4.2.4

---

README.md

This PR updates the `README.md` file.

4.3 Readme update

---

indexer_certs_creator/config/entrypoint.sh
wazuh-indexer/config/config.sh

This PR updates the Wazuh cert tool command and certificates directory name according to changes made in the Cert tool.
Related PR: https://github.com/wazuh/wazuh-packages/pull/1352.
This was manually tested.

Cert tool updates

---

single-node/docker-compose.yml

This PR fix dashboard configuration for single node deploy

Fix dashboard

---

build-docker-images/wazuh-dashboard/config/config.yml
build-docker-images/wazuh-indexer/config/config.yml
multi-node/config/wazuh_indexer_ssl_certs/certs.yml
single-node/config/wazuh_indexer_ssl_certs/certs.yml

Hello team,
We have modified the config.yml format to match issue https://github.com/wazuh/wazuh-packages/issues/1413 suggested format.
We have tested single-node and multi-node with good results.
Closes #609

Changed config.yml format

---

build-docker-images/wazuh-indexer/config/opensearch.yml
multi-node/config/wazuh_indexer/wazuh1.indexer.yml
multi-node/config/wazuh_indexer/wazuh2.indexer.yml
multi-node/config/wazuh_indexer/wazuh3.indexer.yml
single-node/config/wazuh_indexer/wazuh.indexer.yml

This PR is related to https://github.com/wazuh/wazuh-packages/issues/1469

Remove plugin from opensearch.yml

---

build-docker-images/wazuh-dashboard/config/opensearch_dashboards.yml
multi-node/config/wazuh_dashboard/opensearch_dashboards.yml
single-node/config/wazuh_dashboard/opensearch_dashboards.yml

This PR is related to https://github.com/wazuh/wazuh-packages/issues/1470

Disable multitenancy

---

build-docker-images/wazuh-manager/Dockerfile

This PR Fix url for repository key in Wazuh Manager Dockerfile

Fix packages-dev key in Dockerfile

---

build-docker-images/wazuh-indexer/Dockerfile

This PR modifies the permissions of the config directory and some configuration files of Wazuh indexer.
Issue related https://github.com/wazuh/wazuh-docker/issues/621

Change config file permissions

---

build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init

This PR solves the error presented at the start of Wazuh Manager
Closes https://github.com/wazuh/wazuh-docker/issues/622

Error while copying multigroups files during second Docker deployment

---

build-docker-images/wazuh-dashboard/Dockerfile

This PR corrects the address where the Wazuh app files are obtained in the dashboard

Change dashboard repository

---

build-docker-images/wazuh-dashboard/Dockerfile

This PR adds the necessary dependencies for Wazuh dashboard to generate reports

Add dependencies for Wazuh dashboard

---

multi-node/config/wazuh_dashboard/wazuh.yml
multi-node/docker-compose.yml
single-node/config/wazuh_dashboard/wazuh.yml
single-node/docker-compose.yml

This PR modifies the user with which the Wazuh Manager API is configured and with which the Wazuh dashboard connects to the API
Closes https://github.com/wazuh/wazuh-docker/issues/632

Change acme-user

---

multi-node/Migration-to-Wazuh-4.3.md

This PR corrects a data of the migration .md about the version of the product to take for the creation of the volumes
Closes https://github.com/wazuh/wazuh-docker/issues/634

Change doc migration

---

wazuh/Dockerfile
wazuh/config/01-wazuh.sh
wazuh/config/create_user.py

Hello team,
This PR adapts cloud to Wazuh v4.3
Regards

Adapt cloud 4.3

---

multi-node/config/wazuh_cluster/wazuh_manager.conf
multi-node/config/wazuh_cluster/wazuh_worker.conf
single-node/config/wazuh_cluster/wazuh_manager.conf

This PR eliminates the whitelist lines that are not necessary for the deployment of the stacks.

Fix whitelist in 4.3

---

LICENSE
README.md
build-docker-images/docker-compose.yml
build-docker-images/wazuh-dashboard/Dockerfile
build-docker-images/wazuh-dashboard/config/config.sh
build-docker-images/wazuh-dashboard/config/entrypoint.sh
build-docker-images/wazuh-dashboard/config/wazuh.yml
build-docker-images/wazuh-dashboard/config/wazuh_app_config.sh
build-docker-images/wazuh-indexer/Dockerfile
build-docker-images/wazuh-indexer/config/config.sh
build-docker-images/wazuh-indexer/config/entrypoint.sh
build-docker-images/wazuh-indexer/config/securityadmin.sh
build-docker-images/wazuh-manager/Dockerfile
build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init
build-docker-images/wazuh-manager/config/etc/cont-init.d/1-config-filebeat
build-docker-images/wazuh-manager/config/permanent_data.sh
indexer-certs-creator/Dockerfile
indexer-certs-creator/config/entrypoint.sh
multi-node/docker-compose.yml
multi-node/generate-indexer-certs.yml
single-node/docker-compose.yml
single-node/generate-indexer-certs.yml

This PR aims to update the copyright format.

Changed copyright format

---

build-docker-images/wazuh-manager/Dockerfile

Related https://github.com/wazuh/wazuh-packages/issues/1563
This PR updates the version of the Filebeat module.

Update filebeat module version

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.2.7
Regards

Update Wazuh version to v4.2.7

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.3.2
Regards

Update Wazuh version to v4.3.2

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.3.4
Best Regards

Update Wazuh version to v4.3.4

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.3.5.
Regards

Update Wazuh version to v4.3.5

---

build-docker-images/wazuh-manager/config/filebeat.yml

|Related issue|
|---|
| [#1665](https://github.com/wazuh/wazuh-packages/issues/1665) |
Some users have reported problems with Filebeat after installing wazuh related to SIGABRT.
The error it throws is "filebeat[21584]: SIGABRT: abort"
Until now, the error could only be reproduced on systems that have GLIBC v2.35 installed.
After an analysis it was found that the way to solve it is to add the following to the Filebeat template:
```
seccomp:
default_action: allow
syscalls:
- action: allow
names:
- rseq
```
Tests were performed on all recommended systems and a few more. The tests consisted of trying to reproduce the error and then applying the changes to the Filebeat template. Then check, if the error could be reproduced, it is not generated anymore; and if it couldn't be reproduced, that …

Add fix to avoid GLIBC crash

---

indexer-certs-creator/config/entrypoint.sh

This PR fixes the uid and gid of the certificates created for the Wazuh manager deployment

Fix certificate generator

---

wazuh/config/01-wazuh.sh

Hi team
this PR solves queue/rids problems when updating from 4.2.X
base: cloud-1.16
changes branch : cloud-1.16-fix-permissions-queue

Fix Update Wazuh  v4.3.6 - Permissions queue

---

build-docker-images/wazuh-manager/config/etc/cont-init.d/1-config-filebeat

This PR fixes the filebeat.yml file parameters replacement

Filebeat parameters

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.3.6-debug.
Regards

Update Wazuh version to v4.3.6-debug

---

multi-node/config/wazuh_dashboard/wazuh.yml
single-node/config/wazuh_dashboard/wazuh.yml

This PR adds a double quote on Wazuh API password into single and multi node deployment

Add Double Quote on password

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.3.10.
Best Regards

Adapt cloud to Wazuh v4.3.10

---

build-docker-images/wazuh-indexer/config/config.sh

This PR remove Xms and Xmx parameter into jvm.options from Docker Wazuh indexer image build
Related Issue https://github.com/wazuh/wazuh-docker/issues/753

Remove Xms and Xmx parameter into jvm.options

---

README.md

Indexer password updated in README.md

---

build-docker-images/wazuh-dashboard/config/dl_base.sh
build-docker-images/wazuh-indexer/config/config.sh

This PR modifies the base path for Wazuh Dashboard and Wazuh Indexer image creation.

Modify base path

---

.github/workflows/push.yml
README.md

This PR modifies Indexer password into README.md file.

Update indexer password

---

.github/workflows/trivy-dashbaord-4-4.yml
.github/workflows/trivy-indexer-4-4.yml
.github/workflows/trivy-manager-4-4.yml

This PR changes the schedule from Vulnerability test Jobs.
Related Issue #773

Change schedule 

---

build-docker-images/wazuh-dashboard/config/dl_base.sh
build-docker-images/wazuh-indexer/config/config.sh

This PR modifies the path of repositories variables for Wazuh dashboard and indexer image builder

Change dashboard and indexer base repository

---

CHANGELOG.md
wazuh/Dockerfile

Hi team, 
This PR solves issue [#10338](https://github.com/wazuh/wazuh-saas/issues/10338) 
Regards,
Pablo

[Services][Environments] Adapt cloud to Wazuh v4.4 - New environments

---

CHANGELOG.md
wazuh/Dockerfile

Hi team, 
This PR solves issue [#10771](https://github.com/wazuh/wazuh-saas/issues/10771) 
Regards,
Pablo

[Services][Environments] Adapt Cloud to Wazuh v4.4 - Analyze and fix the detected errors

---

wazuh/Dockerfile

Hi team, 
This PR solves issue [#10030](https://github.com/wazuh/wazuh-saas/issues/10030) 
Regards,
Pablo

[Services][Environments] Adapt cloud to Wazuh v4.4

---

CHANGELOG.md

This PR modifies the changelog link for v4.3.11 deploy

Change link for changelog

---

wazuh/Dockerfile

Hello team,
This PR adapts cloud to Wazuh v4.3.11. #[11181](https://github.com/wazuh/wazuh-saas/issues/11181)
Regards,
Gustavo.

Adapt cloud to Wazuh v4.3.11

---

CHANGELOG.md
README.md

This PR merges `4.4` into `4.5`.
Related: https://github.com/wazuh/wazuh/issues/17281.

Merge `4.4` into `4.5`

---

wazuh/Dockerfile

This PR solves [#11532](https://github.com/wazuh/wazuh-saas/issues/11532)

Adapt cloud code to v4.4.4

---

.github/workflows/trivy-dashboard-4-4.yml
.github/workflows/trivy-indexer-4-4.yml
.github/workflows/trivy-manager-4-4.yml

This PR bumps branch version for Trivy scan

Bump branch for trivy scan

---

wazuh/Dockerfile

Hi team, 
This PR solves issue [#11824](https://github.com/wazuh/wazuh-saas/issues/11824) 
Regards,
Pablo

Adapt cloud code to v4.4.5

---

multi-node/config/wazuh_cluster/wazuh_manager.conf
multi-node/config/wazuh_cluster/wazuh_worker.conf
single-node/config/wazuh_cluster/wazuh_manager.conf

This PR delete update_from_year parameter for Wazuh install
Closes https://github.com/wazuh/wazuh-docker/issues/909

Delete update_from_year parameter

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

This PR adds ulimit parameter into Docker compose deploy, into wazuh.manager service

Modify ulimit

---

indexer-certs-creator/config/entrypoint.sh

This PR change typos in certificates generator image.

Typos in the script in charge of create Wazuh indexer's certificates

---

.github/workflows/trivy-dashboard.yml
.github/workflows/trivy-indexer.yml
.github/workflows/trivy-manager.yml

This PR modify the hardcoded version for latest release for a query to the Github API

Change repository checkout

---

build-docker-images/wazuh-manager/config/create_user.py

Issue Related https://github.com/wazuh/wazuh/issues/18966

Error in Wazuh Docker startup

---

build-docker-images/wazuh-dashboard/config/opensearch_dashboards.yml
multi-node/config/wazuh_dashboard/opensearch_dashboards.yml
single-node/config/wazuh_dashboard/opensearch_dashboards.yml

This PR is related to https://github.com/wazuh/internal-devel-requests/issues/394.

Dashboard default route update

---

build-docker-images/wazuh-dashboard/config/opensearch_dashboards.yml
multi-node/config/wazuh_dashboard/opensearch_dashboards.yml
single-node/config/wazuh_dashboard/opensearch_dashboards.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1071
The aim of this PR is to bump the 4.8.0 branch into the master branch.

Merge 4.8.0 into master

---

build-docker-images/wazuh-dashboard/config/wazuh.yml

Related: https://github.com/wazuh/wazuh-automation/issues/1332
The aim of this PR is to update the `wazuh-kibana-app` references to `wazuh-dashboard-plugins`.

Updated wazuh-kibana-app reference

---

wazuh/Dockerfile

Hi team,
This PR solves [#12193](https://github.com/wazuh/wazuh-saas/issues/12193)
Regards,

Adapt cloud code to v4.5.2

---

wazuh/Dockerfile

Hi team,
This PR solves [#12799](https://github.com/wazuh/wazuh-saas/issues/12799)
Regards,

Adapt cloud code to v4.5.3

---

wazuh/Dockerfile

Hi team,
This PR solves [#12920](https://github.com/wazuh/wazuh-saas/issues/12920)
Regards,

Adapt cloud code to v4.5.4

---

wazuh/Dockerfile

Hi team,
This PR solves [#12833](https://github.com/wazuh/wazuh-saas/issues/12833
)
Regards,

Adapt cloud code to v4.5

---

build-docker-images/wazuh-dashboard/config/wazuh.yml

Change occurrences of ```wazuh-kibana-app``` to ```wazuh-dashboard-plugins```
[Issue #337](https://github.com/wazuh/internal-devel-requests/issues/337)

Update links to wazuh-kibana-app repo

---

README.md
build-docker-images/wazuh-indexer/Dockerfile
build-docker-images/wazuh-indexer/config/action_groups.yml
build-docker-images/wazuh-indexer/config/config.sh
build-docker-images/wazuh-indexer/config/roles.yml
build-docker-images/wazuh-indexer/config/roles_mapping.yml

Related https://github.com/wazuh/wazuh-packages/issues/2552

Updated security config files

---

build-docker-images/wazuh-indexer/config/ism-check.sh

This PR modifies `ism_check.sh` script to add more options into ISM policies deploy and be able to use this parameters into the`docker-compose.yml`  file.
Related Issue https://github.com/wazuh/wazuh-docker/issues/1115.
test: https://github.com/wazuh/wazuh-docker/issues/1115#issuecomment-1812429134

[ISM Rollover] Update the ism-check.sh script to accept all parameters

---

build-docker-images/wazuh-manager/Dockerfile
build-docker-images/wazuh-manager/config/filebeat_module.sh

This PR adds a check version for Filebeat wazuh module download.
Related Issue https://github.com/wazuh/wazuh-docker/issues/1119

Update Filebeat module download URL

---

wazuh/config/create_user.py

Issue Related https://github.com/wazuh/wazuh/issues/18966
Ref: https://github.com/wazuh/wazuh/issues/18966

Fix create_user.py

---

wazuh/Dockerfile

Fix Dockerfile

---

wazuh/Dockerfile

Adapt to 4.7.1

---

.github/workflows/push.yml
build-docker-images/wazuh-indexer/config/ism-check.sh
build-docker-images/wazuh-manager/config/filebeat.yml

https://github.com/wazuh/wazuh-docker/issues/1183
The aim of this PR is to bump the changes of the 4.8.0 branch to the 4.8.1 branch

Merge 4.8.0 into 4.8.1

---

.github/workflows/push.yml
build-docker-images/wazuh-indexer/config/ism-check.sh
build-docker-images/wazuh-manager/config/filebeat.yml

https://github.com/wazuh/wazuh-docker/issues/1183
The aim of this PR is to bump the changes of the 4.8.2 branch to the master branch

Merge 4.8.2 into master

---

wazuh/Dockerfile

Add 4.7.2 support

---

build-docker-images/wazuh-manager/config/etc/cont-init.d/2-manager
multi-node/config/wazuh_cluster/wazuh_manager.conf
multi-node/config/wazuh_cluster/wazuh_worker.conf
single-node/config/wazuh_cluster/wazuh_manager.conf

VD keystore changes

---

README.md

This PR fixes the README adding 4.7.3.

Fix readme 4.7.3

---

wazuh/Dockerfile

[Cloud] Add Wazuh 4.7.3 support

---

build-docker-images/wazuh-dashboard/Dockerfile
build-docker-images/wazuh-indexer/Dockerfile
build-docker-images/wazuh-manager/Dockerfile

This PR updates AL2023 version for new vulnerabilities detected.

Update AL2023 20240304

---

indexer-certs-creator/config/entrypoint.sh

Related issue https://github.com/wazuh/wazuh-docker/issues/1265

Update query about Wazuh manager cont names

---

build-docker-images/wazuh-manager/config/etc/cont-init.d/2-manager

Related issue https://github.com/wazuh/internal-devel-requests/issues/513

Delete create_user.py script

---

.github/workflows/push.yml

This PR fixes the failed step on PR test.
Related issue https://github.com/wazuh/wazuh-docker/issues/1253

Fix PR test

---

.github/workflows/push.yml
build-docker-images/build-images.sh
build-docker-images/wazuh-dashboard/Dockerfile
build-docker-images/wazuh-indexer/Dockerfile
build-docker-images/wazuh-manager/Dockerfile
build-docker-images/wazuh-manager/config/check_repository.sh
build-docker-images/wazuh-manager/config/permanent_data.env
indexer-certs-creator/config/entrypoint.sh
multi-node/config/wazuh_cluster/wazuh_manager.conf
multi-node/config/wazuh_cluster/wazuh_worker.conf
multi-node/generate-indexer-certs.yml
single-node/generate-indexer-certs.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1281

Merge 4.8.2 into 4.9.0

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Issue related https://github.com/wazuh/wazuh-docker/issues/1302

Rename docker image for beta6

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Issue related https://github.com/wazuh/wazuh-docker/issues/1302

Rename docker image for 4.8.0

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1308

Updated tag for 4.7.4 RC1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1308

Reverted tag for 4.7.4 RC1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Issue related https://github.com/wazuh/wazuh-docker/issues/1315

Change image version

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Issue related https://github.com/wazuh/wazuh-docker/issues/1315

Rollback image name

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1330

Change image tag for rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1330

rollback image tag

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1348

Commit rc1 image version

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1348

Rollback rc1 image version

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image tag

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image tag

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1357

Commit image version rc3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1357

Rollback image version rc3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1363

Commit image version rc2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1363

Rollback image version rc2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1381

Changed image tag for 4.8.0-rc4

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1381

Reverted image tag for 4.8.0-rc4

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1398

Changed image tag for 4.9.0-alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1398

Reverted image tag from 4.9.0-alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1410

Changed image tag for 4.8.1 RC1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1410

Reverted image tag for 4.8.1 RC1

---

.github/.goss.yaml
.github/workflows/push.yml
build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init

This PR generates keystore certificates and keys and verifies the current keystore.
Related issue https://github.com/wazuh/wazuh-docker/issues/1414

Add new keystore certificate

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related Issue https://github.com/wazuh/wazuh-docker/issues/1417

Change image version por rc2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related Issue https://github.com/wazuh/wazuh-docker/issues/1417

Rollback image version

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1430

Changed image tag for `4.9.0-alpha2`

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.8.1 RC3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.8.1 RC3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.8.1-RC4

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.8.1 RC4

---

build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init

Merge 4.8.1 into 4.9.0

---

README.md

Updated files of README.MD

---

README.md

Merge 4.9.0 into master

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.9.0 Alpha3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

related÷ https://github.com/wazuh/wazuh-docker/issues/1469

Changed image tag for 4.9.0 Beta1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related: https://github.com/wazuh/wazuh-docker/issues/1469

Revert image tag for 4.9.0 Beta1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.9.0 beta2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.9.0 beta2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Issue related https://github.com/wazuh/wazuh-docker/issues/1485

Change image tag to RC1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Issue related https://github.com/wazuh/wazuh-docker/issues/1485

Revert image tag

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.9.0-RC1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.9.0-RC1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.9.0-rc2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.9.0-rc2

---

build-docker-images/build-images.yml

This PR modify the `WAZUH_TAG_REVISION` env variable for use revision 2 of Wazuh dashboard RPM package.
Related Issue https://github.com/wazuh/wazuh-docker/issues/1517

Modify Wazuh dashboard Revision

---

.github/workflows/Procedure_push_docker_images.yml

This PR merges the `4.10.0` branch contents into the `master` branch

Maintenance/5651 merge 4.10.0 into master

---

build-docker-images/wazuh-dashboard/config/check_repository.sh
build-docker-images/wazuh-indexer/config/check_repository.sh
build-docker-images/wazuh-manager/Dockerfile
build-docker-images/wazuh-manager/config/check_repository.sh
build-docker-images/wazuh-manager/config/filebeat_module.sh

This PR modifies the repository checking script for building Wazuh Docker images.
Related Issue https://github.com/wazuh/wazuh-docker/issues/1509

Modify check repository script

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Add rc1 tag to docker-compose files

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert rc1 tag from docker compose files

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.10.0-alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.10.0-alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

related: https://github.com/wazuh/wazuh-docker/issues/1547
Update Wazuh docker images to -rc2 version

Updated Wazuh images to -rc2 version

---

build-docker-images/wazuh-manager/config/etc/cont-init.d/2-manager

This PR aims to add the changes done in https://github.com/wazuh/wazuh-docker/pull/1526. These changes were pushed to `4.9.0` branch but not added to `4.9.1` so in the docker test done here: https://github.com/wazuh/wazuh-docker/issues/1554 have the same issue due to these unmerged changes.
These changes, in addition to having been previously tested for version `4.9.0`, have also been tested in version `4.9.1`: 
- https://github.com/wazuh/wazuh-docker/issues/1554#issuecomment-2391156448
- #1554

Revert create_user.py script deletion

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Changed image tag for 4.9.1-rc3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Reverted image tag for 4.9.1-rc3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

This PR merges a bump of docker-compose image tag versions
More information can be found in the related issue: https://github.com/wazuh/wazuh-docker/issues/1570

Update image tag versions to 4.10.0-alpha2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1574

Change image tag for 4.9.1-rc4

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1574

Revert image tag for 4.9.1-rc4

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change image tag for 4.10.0-alpha2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert image tag for 4.10.0-alpha2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related Issue https://github.com/wazuh/wazuh-docker/issues/1596

Change images tag for 4.9.2 rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Related Issue https://github.com/wazuh/wazuh-docker/issues/1596

Revert images tag for 4.9.2 rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image tag to 4.10.0-alpha3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image tag for 4.10.0-alpha3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image for 4.10.0-beta1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image for 4.10.0-rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.10.0-rc1

---

CHANGELOG.md
build-docker-images/wazuh-dashboard/Dockerfile

Merge 4.10.0 into 4.10.1

---

.github/workflows/push.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1640

Change version for artifact manager actions

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image for 4.10.0-rc2

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.10.0-rc2

---

.github/free-disk-space/action.yml
.github/workflows/push.yml
CHANGELOG.md

Related issue https://github.com/wazuh/wazuh-docker/issues/1642

Change the cleaning disk step

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image for 4.10.0-rc3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.10.0-rc3

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Change docker image for 4.10.1-rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.10.1-rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Image tags changed for alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert image tags for alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert image tags for beta1

---

.github/workflows/trivy-dashboard.yml
.github/workflows/trivy-indexer.yml
.github/workflows/trivy-manager.yml
README.md

This PR updates the references of the branch `master` to `main` 
- #1713

Update references of 'master' branch to 'main'

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.11.0-rc1

---

CHANGELOG.md
README.md

Merge 4.11.1 into 4.12.0

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.11.1-rc2

---

CHANGELOG.md
build-docker-images/wazuh-manager/config/etc/cont-init.d/2-manager

Related issue  https://github.com/wazuh/external-devel-requests/issues/5142#issuecomment-2706342992
``` console
[cont-init.d] 1-config-filebeat: executing... 
Customize Elasticsearch output IP
Configuring username.
Configuring password.
Configuring SSL verification mode.
Configuring Certificate Authorities.
Configuring SSL Certificate.
Configuring SSL Key.
```

Modify wazuh-keystore  use

---

.github/workflows/trivy-dashboard.yml
.github/workflows/trivy-indexer.yml
.github/workflows/trivy-manager.yml
CHANGELOG.md
README.md

**This PR closes the following issue(s):**
- #1735

Remove 'stable' branch ocurrencies

---

CHANGELOG.md
README.md

Merge 4.12.1 into 4.13.0

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert bump image tag 4.12.0-beta1

---

CHANGELOG.md
VERSION.json
multi-node/docker-compose.yml
single-node/docker-compose.yml

Bump revision for 4.12.0-rc1 and add a fogotten changelog entry

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image tag for 4.12.0-rc1

---

CHANGELOG.md

Merge 4.11.1 into 4.12.2

---

CHANGELOG.md
build-docker-images/build-images.yml
build-docker-images/wazuh-agent/Dockerfile
build-docker-images/wazuh-agent/config/check_repository.sh
build-docker-images/wazuh-agent/config/etc/cont-init.d/0-wazuh-init
build-docker-images/wazuh-agent/config/etc/cont-init.d/1-agent
build-docker-images/wazuh-agent/config/etc/services.d/ossec-logs/run
wazuh-agent/config/wazuh-agent-conf
wazuh-agent/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1792

Add Wazuh agent image build and deploy

---

.github/workflows/Procedure_push_docker_images.yml
.github/workflows/push.yml
CHANGELOG.md

Reverts wazuh/wazuh-docker#1809

Revert "Add wazuh agent test and push"

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert image tag for 4.10.2-rc1

---

.github/workflows/Procedure_push_docker_images.yml
CHANGELOG.md

close https://github.com/wazuh/internal-devel-requests/issues/2435
Updated docker/login-action module to v3

Updated docker/login-action module

---

CHANGELOG.md

Remove 4.12.2 references from 4.14.0 branch

---

VERSION.json

Issue: https://github.com/wazuh/wazuh-docker/issues/1860

Bump test/1860-integrate-bumper-script-via-github-action branch

---

VERSION.json
multi-node/docker-compose.yml
single-node/docker-compose.yml

Bump revision and change image tag for 4.13.0-alpha1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

Revert docker image for 4.13.0-alpha1

---

.github/workflows/4_bumper_repository.yml
CHANGELOG.md
multi-node/config/wazuh_cluster/wazuh_manager.conf
multi-node/config/wazuh_cluster/wazuh_worker.conf
single-node/config/wazuh_cluster/wazuh_manager.conf
tools/repository_bumper.sh

Related: https://github.com/wazuh/wazuh-docker/issues/1886

Merge 4.13.1 into 4.14.0

---

CHANGELOG.md
build-docker-images/wazuh-manager/config/permanent_data.env

Related issue https://github.com/wazuh/wazuh-docker/issues/1882

Add permanent_data exceptions

---

VERSION.json
multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2625

Bump test/554-test branch

---

VERSION.json
multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2654

Bump 4.13.0 branch

---

multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Revert docker tag for v4.13.0-beta1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Change docker image tag for 4.13.0-rc1

---

multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Related Issue https://github.com/wazuh/wazuh-docker/issues/1936

Revert rc2 stage into 4.13.0 branch

---

multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Change docker image tag for 4.13.0-rc3

---

VERSION.json
multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Revert rc4 changes

---

build-docker-images/wazuh-manager/config/permanent_data.env
multi-node/docker-compose.yml
single-node/docker-compose.yml

Related Issue https://github.com/wazuh/wazuh-docker/issues/1962
Bump rc1 stage

Add PERMANENT_DATA exception and bump rc1 stage

---

multi-node/docker-compose.yml
single-node/docker-compose.yml

This PR revert tags for rc1 stage

Revert Tags rc1

---

CHANGELOG.md
build-docker-images/wazuh-manager/config/permanent_data.env

Related issue https://github.com/wazuh/wazuh-docker/issues/1966

Add wazuh-template.json into permanent data exception

---

multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1979

Revert images tags

---

CHANGELOG.md
multi-node/config/wazuh_dashboard/opensearch_dashboards.yml
single-node/config/wazuh_dashboard/opensearch_dashboards.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/1984

Add opensearch_dashboard.yml parameters

---

multi-node/docker-compose.yml
single-node/docker-compose.yml
wazuh-agent/docker-compose.yml

Revert docker image tag for 4.13.0 RC4

---

CHANGELOG.md
multi-node/config/wazuh_dashboard/opensearch_dashboards.yml
single-node/config/wazuh_dashboard/opensearch_dashboards.yml

This PR is related to https://github.com/wazuh/internal-devel-requests/issues/3077

Rollback data source setting

---

CHANGELOG.md
multi-node/config/wazuh_dashboard/opensearch_dashboards.yml
single-node/config/wazuh_dashboard/opensearch_dashboards.yml

This PR is related to: https://github.com/wazuh/internal-devel-requests/issues/3056

Remove dashboard chat setting

---

CHANGELOG.md
indexer-certs-creator/Dockerfile
indexer-certs-creator/README.md
indexer-certs-creator/config/entrypoint.sh
multi-node/generate-indexer-certs.yml
single-node/generate-indexer-certs.yml

Related issue https://github.com/wazuh/wazuh-docker/issues/2026

Wazuh cert tool generator improvements
