wazuh/wazuh-docker

docker-compose.yml, kibana/config/wait-for-it.sh
Added WAZUH_KIBANA_PLUGIN_URL variable to wait-for-it.sh so that kibana plugin installation URL can be overwritten (the default still points to https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.3.0.zip).
This is useful in (most likely corporate) environments where there is no egress to the internet or users just prefer to mirror all software locally.
Could also be useful to test a different version of the plugin.
=> Configurable URL for kibana plugin

docker-compose.yml, kibana/Dockerfile, kibana/config/wait-for-it.sh
The Kibana image does now include all dependencies and has the plugin build in. 
So there is no need for the Kibana container to access the internet or install the plugin on start as it is all included. 
So there was also no need anymore for the http_proxy env variable in docker-compose.yml and the other env variables also. 
This works flawless behind a corp proxy but pls test this for your deployment first.
! This needs the dockerhub kibana image to get updated !
This Fixes #34
=> Improved Kibana Image to include all Dependencies

docker-compose.yml, wazuh/Dockerfile
Fix issue #40 . 
With the intention of making changes in a simpler way in filebeat.yml, we give the option to mount it as a volume.
=> Issue 40.1

README.md, docker-compose.yml, wazuh/config/run.sh
Having a way to mount custom configuration files in the Wazuh manager container will be really useful!
Why do we need a mount point for those files?
* I first tried to mount the `ossec.conf` file at the `/var/ossec/etc/ossec.conf` path, but on the first boot of the container, the [`if [ ! -e "${DATA_PATH}/${ossecdir}" ]`](https://github.com/wazuh/wazuh-docker/blob/master/wazuh/config/run.sh#L38) condition becomes false for the `etc` folder and the initial Wazuh setup in the container fails (the `etc` folder contains only the `ossec.conf` file and some SSL keys).
* Then, I tried to mount the `ossec.conf` file at the `/var/ossec/etc-template/ossec.conf` path, it worked on the initial install, but since I use a persistent storage for the `/var/ossec/data` folder (an AWS EBS drive mounted in …
=> Add a mount point for custom Wazuh configuration files

README.md, docker-compose.yml, wazuh/config/entrypoint.sh
Addresses #57
This method is arguably only slightly less hacky than the two workarounds I added in #57, but it's a sounder strategy for automated installation than either of them.
=> Allow custom scripts or commands before service start

LICENSE
Added this so that this repository actually complies with the license it claims to be under. This is a direct copy of https://github.com/wazuh/wazuh/blob/master/LICENSE with the copyright date changed from 2017 to 2018 to match the copyright dates in some of this repo's source files.
=> added license file to match https://github.com/wazuh/wazuh

wazuh/Dockerfile
ossec expected its user's home directory to be `/var/ossec`. (ossec's old docs (mentioned this in passing)[https://www.ossec.net/docs/manual/agent/agentless-monitoring.html], but I haven't found it anywhere in wazuh's docs yet).
`wazuh/wazuh` doesn't specify a home directory at all for the ossec user, meaning that it defaults to `/home/ossec`, which doesn't exist. This means that the `ssh-keygen` command in the agentless [How It Works](https://documentation.wazuh.com/current/user-manual/capabilities/agentless-monitoring/how-it-works.html) section can't be followed. I've made it so `/var/ossec` is the home directory.
=> Set ossec user's home path

docker-compose.yml, wazuh/Dockerfile
Hello team,
This PR is born from issue #66
We have added the SMTP packages that are missing.
- mailutils
- libsasl2-modules
For its installation, we have to add the universe repository.
Now, these packages will be installed by lifting Wazuh container. 
Regards,
Alfonso
=> Added SMTP packages

wazuh/config/entrypoint.sh
It fixes #76. When using external volumes in docker the outdated internal_options.conf is kept. Because of this and overwrite of the internal_options.conf file with the one of the new version is needed. Also /var/ossec/queue/db/.template.db needs to be deleted in case a change in the database schema.  
To correct this issues a fix is includead in entrypoint.sh. This fix overwrites the  the outdated internal_options.conf with the one of the new version and also deletes  /var/ossec/queue/db/.template.db so when the manager starts the dabase could be regenerated with the new schema.
=> entrypoint.sh updated so docker upgrade is posible

nginx/Dockerfile, nginx/config/entrypoint.sh
Hello team,
To better manage Nginx credentials at Docker and Kubernetes, we have added the necessary environment variables. 
Regards,
=> Add env credentials for nginx

CHANGELOG.md, README.md, docker-compose.yml, kibana/Dockerfile, wazuh/Dockerfile, wazuh/config/entrypoint.sh
Hello team,
This PR updates the Wazuh version to 3.8.0 as requested in issue #96.
The only notable change is the removal of the command that enables **authd**, because it no longer exists. 
Best regards,
=> Upgrade version 3.8.0_6.5.4

CHANGELOG.md, wazuh/Dockerfile
Hello team,
The workaround did in Wazuh Dockerfile:
https://github.com/wazuh/wazuh-docker/blob/master/wazuh/Dockerfile#L81
It's no longer necessary. In version 3.8.0 those lines no longer exist due PR [#2227](https://github.com/wazuh/wazuh/pull/2227)
The issue #83 is solved.
Best regards,
=> Remove cluster.py work around

docker-compose.yml, elasticsearch/Dockerfile, elasticsearch/config/entrypoint.sh, elasticsearch/config/load_settings.sh, kibana/Dockerfile, kibana/config/entrypoint.sh, wazuh/Dockerfile, wazuh/config/entrypoint.sh
Hello team,
This PR solves #108 and creates the Wazuh-Elasticsearch module. This is done to properly separate the tasks concerning each container. The configurations of each container only depend on itself and not on another container. 
To this end, we have transferred the modifications made to the Elasticsearch container from the Kibana container.
We have also added the option of configuring API credentials using environment variables so that they are not embedded in the code. 
We have performed tests of various types:
- Clean deployment.
- Deployment with new API credentials.
- Deployment enabling volumes for Elasticsearch and Wazuh.
- Registration of agents. 
- Verification of the persistence of agent registration, configuration changes and alerts through the use of volumes.
- …
=> Add Wazuh-Elasticsearch

elasticsearch/Dockerfile, elasticsearch/config/entrypoint.sh, elasticsearch/config/load_settings.sh, kibana/Dockerfile, kibana/config/entrypoint.sh, kibana/config/kibana_settings.sh, kibana/config/xpack_config.sh
Hi team,
this PR solves - https://github.com/wazuh/wazuh-saas/issues/41. It adds the capacity of enabling and disabling xpack features mainly at Kibana but also disable by default xpack machinelearning from the elasticsearch image. All these changes happen when the container is created and it is possible to enable and disable xpacks features using environment variables. For example:
```yml
kibana:
build: ./kibana
hostname: kibana
restart: always
environment:
- ELASTICSEARCH_URL=http://elasticsearch:9200
- XPACK_DEVTOOLS=true
- XPACK_CANVAS=false
- XPACK_LOGS=true
```
The docker-compose that can be seen above enables the devtools and logs plugin  at Kibana and disables the canvas plugin. Right now by default devtools, canvas, infraestructure, machinelearning, logs and apm are disabled by …
=> Adding the option to disable some xpack features

kibana/Dockerfile, kibana/config/entrypoint.sh
Hello team,
This PR solves issue #114.
The Wazuh-Kibana image can now be built using arguments to manage the plugins we want to have enabled.
```
ARG XPACK_CANVAS="true"
ARG XPACK_LOGS="true"
ARG XPACK_INFRA="true"
ARG XPACK_ML="true"
ARG XPACK_DEVTOOLS="true"
ARG XPACK_MONITORING="true"
ARG XPACK_APM="true"
```
By default, we will have all plugins enabled being the construction command the following:
`$ docker build kibana`
For each plugin we want to disable we'll have to add arguments to the command: 
`$ docker build kibana --build-arg  ARG_KEY_1=ARG_VALUE_1 . . . --build-arg  ARG_KEY_n=ARG_VALUE_n`
To disable all plugins the command would be serious:
`$ docker build kibana --build-arg XPACK_CANVAS="false" --build-arg  XPACK_LOGS="false" --build-arg XPACK_INFRA="false" --build-arg …
=> Wazuh-Kibana customizable at plugin level

wazuh/Dockerfile
Hi team,
this PR fix some missing settings at the refractor Dockerfile. The following was missing and was added at this PR:
- Environment variables: [API_USER and API_PASS](https://github.com/wazuh/wazuh-docker/blob/10ae694a92878d3abf127f70c6f5cf20a9bc6795/wazuh/Dockerfile#L6)
- Missing packages: [mailutils libsasl2-modules](https://github.com/wazuh/wazuh-docker/blob/10ae694a92878d3abf127f70c6f5cf20a9bc6795/wazuh/Dockerfile#L33)
- Filebeat config file
Also I added the [universe repository](https://github.com/wazuh/wazuh-docker/blob/10ae694a92878d3abf127f70c6f5cf20a9bc6795/wazuh/Dockerfile#L28) that is in our actual Wazuh dockerfile.
=> Fixing missing packets, env vars and config file of filebeat

CHANGELOG.md, kibana/Dockerfile, kibana/config/welcome_wazuh.sh
Hello team,
This PR solves issue #131 
First of all we have declared an ARG variable to build the image of Kibana adjusting it to the needs that are required. 
- Kibana Dockerfile 
`ARG CHANGE_WELCOME="false"`
Setting this variable to true will imply the desired changes in the welcome screen. 
After that, we add the script that makes the changes. 
- Kibana change welcome screen script
```
#!/bin/bash
if [[ $CHANGE_WELCOME == "true" ]]
then
rm -rf ./optimize/bundles
kibana_path="/usr/share/kibana"
echo "Set Wazuh app as the default landing page"
echo "server.defaultRoute: /app/wazuh" >> /usr/share/kibana/config/kibana.yml
echo "Redirect Kibana welcome screen to Discover"
sed -i "s:'/app/kibana#/home':'/app/wazuh':g" $kibana_path/src/ui/public/chrome/directives/global_nav/global_nav.html …
```
=> Welcome screen management

CHANGELOG.md, kibana/config/entrypoint.sh, logstash/Dockerfile, logstash/config/entrypoint.sh
Hello team,
This PR solves issue #132.
It was necessary to add certain race conditions for Logstash and Kibana. Both services will wait until the Wazuh alerts template is loaded.
Logstash lacked an entrypoint of its own and we created it, adding the run.sh lines that are no longer needed.
Best regards,
=> New Logstash entrypoint added

docker-compose.yml, nginx/config/entrypoint.sh
Hi team,
In order to set users credentials, before " docker-compose up -d " run (a or b):
a) export NGINX_CREDENTIALS="user1:pass1;user2:pass2;"
b) Set NGINX_CREDENTIALS in docker-compose.yml:
NGINX_CREDENTIALS=user1:pass1;user2:pass2;
=> Setting Nginx docker to support several user/passwords in Kibana

wazuh/config/filebeat.yml
Hi team, 
this PR fixes https://github.com/wazuh/wazuh-kubernetes/issues/32. It adds the [tail_files](https://www.elastic.co/guide/en/beats/filebeat/1.2/configuration-filebeat-options.html#_tail_files) option to the Filebeat config file. Like it is said in the issue the main problem was that the device where the alerts.json was located changed between pods restarts so  filebeat though that it was a new file and starts reading it all over again. With this option the following is expected to happen:
- If the device doesn't change between restarts: the alerts.json file will be readed from the end the first time and the next reboots the  offset will be used to read the file. 
- If the device change: filebeat will  treat alerts.json as if it were new and will start reading  from the end each …
=> Fixing duplicate alerts with kubernetes

CHANGELOG.md, wazuh/Dockerfile
Hello team,
This PR is a workaround for issue #127. 
As long as the installation of the Wazuh manager involves a boot, we can only choose to remove the alerts that are created at that time. 
Best regards,
=> Remove alerts created in build time

docker-compose.yml
LS_HEAP_SIZE does not work for logstash versions >= 5.0.0 use LS_JAVA_OPTS instead.
=> Use LS_JAVA_OPTS instead of old LS_HEAP_SIZE

elasticsearch/config/load_settings.sh
This PR fix - https://github.com/wazuh/wazuh-docker/issues/123. A change was made at the url where the elasticsearch configuration is set. Instead of "elasticsearch" that was set up by docker-compose "localhost| is used because when the container is run outside of docker-compose it will enter in a infinite loop because it cant resolve "elasticsearch".
=> Fixing docker run loop at the elasticsearch container

CHANGELOG.md, README.md, elasticsearch/Dockerfile, elasticsearch/config/config_cluster.sh, elasticsearch/config/entrypoint.sh, elasticsearch/config/load_settings.sh
Hello team,
This PR solves #145 
Best regards,
=> Add Elasticsearch cluster configuration

wazuh/Dockerfile
Hi team!
This PR solves issue https://github.com/wazuh/wazuh-docker/issues/152 .
It removes `.log` and `.json` files from the following paths:
```
/var/ossec/logs/alerts/*/*/
/var/ossec/logs/archives/*/*/
/var/ossec/logs/firewall/*/*/
```
Best regards,
Mayte Ariza
=> Removing files from Wazuh image

wazuh/Dockerfile
Hi team!
This PR solves issue https://github.com/wazuh/wazuh-docker/issues/168. It removes from **Wazuh image** all the `log files` contained in the following paths:
```
"logs/alerts/*/*",
"logs/api/*/*",
"logs/archives/*/*",
"logs/cluster/*/*",
"logs/firewall/*/*",
"logs/ossec/*/*"
```
Best regards,
Mayte Ariza
=> Removing log files from Wazuh image

kibana/config/kibana_settings.sh
Hello team,
this PR allows port customization for Kibana - Elasticsearch communication.
Useful when you are not using Elasticsearch default port.
Regards.
=> Allow port change for elasticsearch url in kibana

docker-compose.yml, kibana/config/xpack_config.sh, wazuh/Dockerfile, wazuh/config/01-config_filebeat.sh
Hi folks,
This PR enables the ability to change the Elasticsearch output (`hosts`) if the `ELASTICSEARCH_URL` environment variable is set in the Wazuh container:
```
wazuh:
image: wazuh/wazuh:3.9.2_7.1.1
hostname: wazuh-manager
restart: always
ports:
- "1514:1514/udp"
- "1515:1515"
- "514:514/udp"
- "55000:55000"
environment:
- ELASTICSEARCH_URL=https://customelk.com:9300
```
That configuration will change this option in the `filebeat.yml` configuration file:
```
output.elasticsearch:
hosts: ['https://customelk.com:9300']
```
This PR also removes missing components of Logstash, related issue here: #191 
Cheers
=> Changing Filebeat configuration if environment variable is set

wazuh/config/01-wazuh.sh
Hi team!!
This PR solves issue https://github.com/wazuh/wazuh-docker/issues/205. Read and write permissions are granted for `/var/ossec` path in order to modify files properly using the Wazuh API .
Best regards,
Mayte Ariza
=> Grant read and write permissions for group 

wazuh/config/01-wazuh.sh
Hi team!!
This PR solves issue https://github.com/wazuh/wazuh-docker/issues/208. It is checked if every file contained in _PERMANENT_DATA_DEL_  exists before removing it to avoid exiting the script execution.
Best regards,
Mayte Ariza.
=> Check if file exists before removing it

docker-compose.yml, elasticsearch/Dockerfile, elasticsearch/config/config_cluster.sh
Hello team,
This PR fixes #195. The cluster configuration was reinserted to the `elasticsearch.yml` file when the containers were restarted. It's been solved by implementing the following logic:
- If the cluster isn't enabled using the `ELASTIC_CLUSTER` variable, then a single host configuration is set.
```
discovery.type: single-node
```
- If the cluster is enabled, then set a production configuration.
The reinserted data bug is fixed by deleting the previous configuration before inserting a new one:
```
sed -i '/# cluster node/,/# end cluster config/d' $elastic_config_file
remove_single_node_conf(){
if grep -Fq "discovery.type" $1; then
sed -i '/discovery.type\: /d' $1 
fi
}
```
An example of a cluster configuration could be illustrated by the following `docker-compose.yml`:
``` …
```
=> Fixed duplicated cluster configuration

kibana/Dockerfile, kibana/config/kibana_settings.sh
Hello team,
This PR mainly fixes #217 and also updates the RESTful API to the `v2` version. Since Elastic was updated, it was breaking our Docker Kibana build. Now the installation of the Wazuh plugin is done with the flag:
```
--allow-root
```
Cheers
=> Adapt Kibana image to v7.2.0

docker-compose.yml, wazuh/Dockerfile
Hello team,
We need the option to install debug and gdb packages to be able to debug errors more accurately when lifting environments using K8S.
This PR meets those needs. 
Best regards,
=> K8s debug packages and gdb

docker-compose.yml
The nginx imageimage: wazuh/wazuh-nginx:3.9.5_7.3.0 doesn't exists, shall we use image: wazuh/wazuh-nginx:3.9.5_7.3.0-oss
=> Nginx image has a wrong name

wazuh/config/01-wazuh.sh
Hi team!!
This PR solves issue https://github.com/wazuh/wazuh-docker/issues/225.  It **removes recursively write permissions** for _group and other_ in `/var/ossec/integrations` folder after granting read and write permissions recursively in `/var/ossec/` path.
Best regards,
Mayte Ariza
=> Removed write permissions for group and other in Integrations folder

kibana/config/20-entrypoint.sh
Hi team, 
This PR adds `server.ssl.supportedProtocols` to Kibana in order to avoid TLSv1.
Best regards,
Josemi
=> Added TLS version filter

wazuh/config/01-wazuh.sh
Hi team!!
This **PR** fixes an error when copying the **exclusion files** from `permanent_data.env` to their original path. 
Best regards,
Mayte Ariza
=> Copying exclusion data with subfolders between the mount point and the file

wazuh/config/permanent_data.env
Hi team!!!
This PR adds `/var/ossec/wodles` path to PERMANENT_DATA variable in order to keep **permissions**, **ownership** and **files**.
Best regards,
Mayte Ariza
=> Add wodles to permanent_data

wazuh/config/01-wazuh.sh, wazuh/config/02-set_filebeat_destination.sh
Hello team,
Before the option to change the Filebeat output was done in a process prior to copying the configuration depending on the destination (Logstash or Elasticserach) therefore had no effect.
We have changed that code section so that it is done once the final configuration is established. 
Best regards,
=> Fixed the option to change Filebeat output

logstash/config/01-wazuh.conf
Hello team,
This PR adds to the Logstash image a new filter in the pipeline to avoid errors produced by the data published field of vulnerability detector. 
Best regards,
=> Add workaround for vulnerability detector data published field

elasticsearch/Dockerfile
Hello,
This PR fixes two problems I had with the installation of the S3 plugin.
- The first one is related to [ARG before FROM](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) which is not taken into account in the rest of the Dockerfile.
- The second one was related to `${bin/elasticsearch-plugin install --batch S3_PLUGIN_URL}` which did nothing
=> Fix S3 plugin installation in Elasticsearch

nginx/config/entrypoint.sh
This PR fixes #305 
The `htpasswd` utility supports batch mode `-b` which takes username and password as CLI arguments so there's no need to use a pipe.
This change was already tested locally.
=> Use batch mode on htpasswd

nginx/config/entrypoint.sh
This PR fixes #307 
Enables HTTP v2 on the nginx container
=> Enable HTTP2 protocol

wazuh/config/entrypoint.sh
Hello team,
This PR adds a trap to be able to kill the initial process of the wazuh container, in order to manage errors in the start of the container. 
Best regards,
=> Add trap for sbin my init 

elasticsearch/config/35-entrypoint_load_settings.sh
Hi team!!!
This PR creates the _.wazuh_ index with **0 replicas** before setting the Wazuh API credentials to avoid the cluster state switching to yellow in Elasticseaerch single-node clusters.
Best regards,
Mayte Ariza
=> Create .wazuh index before setting the API credentials

wazuh/Dockerfile, wazuh/config/01-wazuh.sh, wazuh/config/85-save_wazuh_version.sh, wazuh/config/permanent_data.env
Hi team!!
This PR improves the Wazuh image to solve some issues that may appear when updating the environment:
- It **adds** the following files in `PERMANENT_DATA_EXCP`:
- /var/ossec/queue/vulnerabilities/dictionaries/cpe_helper.json
- /var/ossec/queue/vulnerabilities/dictionaries/msu.json.gz
- It **adds** the following files in `PERMANENT_DATA_DEL`:
- /var/ossec/var/db/global.db*
- /var/ossec/var/db/.profile.db*
- /var/ossec/var/db/.template.db*
- /var/ossec/var/db/agents/*
- /var/ossec/wodles/cve.db
- /var/ossec/queue/vulnerabilities/cve.db
- We have added a new file, `/var/ossec/etc/VERSION`, in order to check the previous Wazuh version installed in the pod.
Best regards,
Mayte Ariza
=> Improve Wazuh image: overwriting and removing files

wazuh/config/00-wazuh.sh, wazuh/config/data_dirs.env
This PR fixes #349 by adding the agentless dir to our list of persistent locations.
=> Save agentless state

wazuh/config/permanent_data.env
Hi team!!!
This PR adds `/var/ossec/var/db` path to PERMANENT_DATA variable in order to keep **mitre.db** when mounting the path `/var/ossec/var/db` .
Best regards,
Mayte Ariza
=> Add /var/ossec/var/db to permanent data

wazuh/Dockerfile
Hello team,
This PR updates Wazuh original image for cloud to Wazuh 3.13.1 and filebeat to 7.8.0 for Opendistro 1.9.0.
Best regards
=> Adapt wazuh to 3.13.1 and filebeat to 7.7.0

elasticsearch/Dockerfile, elasticsearch/config/config_cluster.sh
Hello,
This PR add CLUSTER_NETWORK_HOST environment variable to configure `network.host` for Elasticsearch Cluster.
Example: `CLUSTER_NETWORK_HOST=_local_,192.168.1.111`
If CLUSTER_NETWORK_HOST is not set, then 0.0.0.0.0 is used as before.
Problem:
If an Elasticsearch container can recognize multiple IP addresses, it may respond the local IP of the docker network and other Elasticseach containers(node) are not be able to join the cluster.
- Docker Host 1: elasticsearch(es01) + network_mode: host
```
elasticsearch:
image: wazuh/wazuh-elasticsearch:3.13.1_7.8.0
hostname: elasticsearch
extra_hosts:
- "elasticsearch:192.168.1.111"
- "es01:192.168.1.111"
- "es02:192.168.1.112"
restart: always
ports:
- "9200:9200"
- "9300:9300"
environment:
- "ES_JAVA_OPTS=-Xms1g -Xmx1g"
- ELASTIC_CLUSTER=true …
```
=> Add CLUSTER_NETWORK_HOST environment variable to configure network.host

wazuh/Dockerfile, wazuh/config/01-config_filebeat.sh
This PR fixes #374 
Filebeat module is now installed on build stage.
Also pinned the phusion/baseimage to version `0.10.2` since the tag `latest` was deleted recently.
=> Fix filebeat installation

wazuh/config/filebeat_to_logstash.yml
Hello team,
This PR allows read archives.json events in Filebeat. Option disabled by default. 
Regards
=> Read archives events in Filebeat

wazuh-opendistro/config/etc/cont-init.d/0-wazuh-init
- This PR implements #261 for devel-rework
- Removes legacy code to trap stop signal, during this startup sequence the Wazuh processes are not running yet
=> Implement PR 261 on rework branch

wazuh/config/00-wazuh.sh
We want to use Kubernetes secrets for passing all Wazuh credentials (Issue: https://github.com/wazuh/wazuh-kubernetes/issues/29)
For this I have tweaked one of the entrypoint scripts to dynamically passed the key from Kubernetes pod spec (https://github.com/wazuh/wazuh-kubernetes/pull/108).
- Replacing the placeholder for cluster key in ossec.conf with an environment variable `WAZUH_CLUSTER_KEY`
=> Updating Wazuh cluster key dynamically

kibana-odfe/config/wazuh_app_config.sh
This PR changes the default user for the kibana app to `wazuh-wui` since it's the one with `rus_as` support.
=> Set wazuh-wui as default user for the app

production_cluster/wazuh_cluster/wazuh_manager.conf, production_cluster/wazuh_cluster/wazuh_worker.conf, wazuh-odfe/config/etc/cont-init.d/0-wazuh-init, wazuh-odfe/config/etc/cont-init.d/2-manager
This PR closes #418  and #421
- Update references to deprecated `ossec-` prefix in favor of `wazuh-` prefix
=> Adopt Wazuh standard on tool names

wazuh-odfe/Dockerfile
This PR bumps the s6-overlay version to latest release
=> Bump s6-overlay version

wazuh-odfe/config/etc/cont-init.d/2-manager
This PR fixes #433 
- Re-enable entrypoint scripts (these were lost since 4.0 when we migrated to s6-overlay)
=> Re-enable entrypoint scripts

generate-elasticsearch-certs.yml, kibana/Dockerfile, kibana/config/entrypoint.sh, kibana/config/kibana_settings.sh, kibana/config/wazuh.yml, kibana/config/wazuh_app_config.sh, kibana/config/xpack_config.sh, wazuh-odfe/Dockerfile, xpack-compose.yml, xpack/instances.yml
This PR closes #398 
- Backport kibana-xpack image
- Add the ARG `FILEBEAT_CHANNEL` on the wazuh-odfe Dockefile to allow for both regular filebeat and oss versions.
- Add `xpack-compose.yml` with sample deployment
- Add `generate-elasticsearch-certs.yml` and `xpack/instances.yml` for SSL cert generation
=> Add images compatible with xpack

wazuh-odfe/Dockerfile
This PR fixes #438 
- Add the `goss` binary for health checks on both Docker and Kubernetes
=> Add goss binary for health checks

.goss.yaml, production_cluster/wazuh_cluster/wazuh_manager.conf, production_cluster/wazuh_cluster/wazuh_worker.conf, wazuh-odfe/Dockerfile, wazuh-odfe/config/etc/cont-init.d/2-manager
Hi team,
This PR closes #448, changes `ossec`, `ossecr` and `ossecm` users and groups to `wazuh`.
Greetings,
Víctor.
=> Rename users and group according to Wazuh standard

README.md
Closes #457
This PR corrects a broken link at `README.md` and removes unused information about basic auth.
=> 457: Broken link fix and removed deprecated information at README  to 5.0

README.md
Closes #457 
This PR corrects a broken link at `README.md` and removes unused information about basic auth.
=> 457: Broken link fix and removed deprecated information at README

production-cluster.yml, production_cluster/elastic_opendistro/elasticsearch-node1.yml, production_cluster/elastic_opendistro/elasticsearch-node2.yml, production_cluster/elastic_opendistro/elasticsearch-node3.yml, production_cluster/ssl_certs/certs.yml
Hi team,
I've made some modifications to the configuration files in order to have an admin keypair to be able to change the Security index of the ODFE plugin.
Now, when generating the certificates with `docker-compose -f generate-opendistro-certs.yml run --rm generator` it will generate an `admin.key` and ` admin.pem` that can be used with the `securityadmin.sh` script to update the security index.
Regards.
=> Add admin keypair to production deployment

wazuh-odfe/config/etc/cont-init.d/0-wazuh-init, wazuh-odfe/config/permanent_data.env
Closes #505 
This PR fixes a problem when upgrading wazuh-docker to 4.2.0 where the persistent volume in `/var/ossec/queue` caused  the manager to be unable to start.
=> Fix 4.2 upgrade

wazuh-odfe/config/etc/services.d/ossec-logs/run
Hello team,
This PR aims to fix an issue where the container stops showing logs after the `ossec.log` file gets rotated.
I have replaced the `tail -f` command with `tail -F` to prevent that:
```shell
-f, --follow[={name|descriptor}]
output appended data as the file grows;
an absent option argument means 'descriptor'
-F     same as --follow=name --retry
```
Regards,
Franco Hielpos
=> Change tail argument to prevent log rotation issues

README.md, kibana-odfe/config/wazuh_app_config.sh, kibana/config/wazuh_app_config.sh
Added environment variable `WAZUH_MONITORING_CREATION` to allow custom configuration of Kibana variable `wazuh.monitoring.creation` inside Docker container.
=> Add environment variable to customize wazuh.monitoring.creation interval

kibana-odfe/config/wazuh_app_config.sh
The other way works too, but it seems pointless to go through extra steps when the if command already does exactly this
=> in bash if already tests exit status is 0 or not

wazuh-odfe/config/create_user.py
This pull request closes #574 .
The related issue reported an error found in a test where a cluster with 1 master node and 1 worker node of Wazuh manager 4.3.0 was set up.
The error showed that the RBAC DB tables did not exist. 
The RBAC DB used to be created when first importing the `orm` module. After the changes done in https://github.com/wazuh/wazuh/pull/11598, the RBAC DB creation is done in the `wazuh-apid.py` script. Therefore, no RBAC DB is created in the `create_user.py` script and when trying to access the DB information, the error is raised.
I have updated the `create_user.py` script to include a call to this function (`create_rbac_db()`).
```
root@wazuh-master:/# cat /var/ossec/api/configuration/admin.json
{
"username": "acme-user",
"password": "MyS3cr37P450r.*-"
}     
``` …
=> Update `create_user.py` script to create the RBAC database before trying to read

indexer-certs-creator/config/entrypoint.sh
closes #613 
After the change on the wazuh_cert_tools.sh (#1443), on the improvement in the format of the config.yml, an error occurred in the generation of the certificates on the docker repository.
The cert_parseYaml function previously returned:
`nodes_indexer_name=wazuh1.indexer nodes_indexer_ip=wazuh1.indexer`
and now it returns:
`nodes_indexer__name=wazuh1.indexer nodes_indexer__ip=wazuh1.indexer`
Correct the greps in docker to parse correctly, as modified in the packages repo
Before changes:
```
fcaffieri@Fede:~/repos/wazuh-docker/multi-node$ docker-compose -f generate-indexer-certs.yml run --rm generator
Pulling generator (wazuh/wazuh-certs-generator:0.0.1)...
0.0.1: Pulling from wazuh/wazuh-certs-generator
e0b25ef51634: Already exists
b5eb3cca99e9: Pull complete
d56f95ba5a4d: …
```
=> Fix parse cert.yml according to wazuh_cert_tools modifications

multi-node/config/wazuh_cluster/wazuh_manager.conf, multi-node/config/wazuh_cluster/wazuh_worker.conf, single-node/config/wazuh_cluster/wazuh_manager.conf
This PR eliminates the whitelist lines that are not necessary for the deployment of the stacks.
=> Fix whitelist in 4.4

build-docker-images/wazuh-manager/config/create_user.py
I came across an issue where the `wazuh/wazuh-odfe:4.2.5` container would fail with the ambiguous error message:
```
ERROR:root:No module 'wazuh' found.
There was an error configuring the API user
```
Patching the `create_user.py` file to not have a blanket catch all exceptions allowed me to find out the real error was (likely file permissions issue):
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```
=> Allow other Exceptions to bubble up a stack trace instead of silently failing in create_user.py

build-docker-images/wazuh-manager/config/filebeat.yml
|Related issue|
|---|
| [#1665](https://github.com/wazuh/wazuh-packages/issues/1665) |
Some users have reported problems with Filebeat after installing wazuh related to SIGABRT.
The error it throws is "filebeat[21584]: SIGABRT: abort"
Until now, the error could only be reproduced on systems that have GLIBC v2.35 installed.
After an analysis it was found that the way to solve it is to add the following to the Filebeat template:
```
seccomp:
default_action: allow
syscalls:
- action: allow
names:
- rseq
```
Tests were performed on all recommended systems and a few more. The tests consisted of trying to reproduce the error and then applying the changes to the Filebeat template. Then check, if the error could be reproduced, it is not generated anymore; and if it couldn't be reproduced, that …
=> Add fix to avoid GLIBC crash

build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init
Hello team,
This PR aims to suggest a solution to fix the persisting permissions/ownership of Ossec user/group when upgrading the Wazuh manager to 4.3.
Regards,
Elwali
=> Fix permissions/ownership issue for Wazuh manager migration (4.2 -> 4.3)

multi-node/config/wazuh_dashboard/wazuh.yml, single-node/config/wazuh_dashboard/wazuh.yml
This PR adds a double quote on Wazuh API password into single and multi node deployment
Related to https://github.com/wazuh/wazuh-docker/issues/714
=> Add Double Quote on password

single-node/config/wazuh_cluster/wazuh_manager.conf
This PR disables cluster option into single node deployment.
Related Issue https://github.com/wazuh/wazuh-docker/issues/807
=> Disable cluster option

multi-node/config/wazuh_cluster/wazuh_manager.conf, multi-node/config/wazuh_cluster/wazuh_worker.conf, single-node/config/wazuh_cluster/wazuh_manager.conf
This PR adds the corresponding AlmaLinux entry in the vulnerability detector default configuration after the changes in [Add support for AlmaLinux in Vulnerability Detector](https://github.com/wazuh/wazuh/pull/16343#top)
#16343.
=> Updating vulnerability detector default configuration with AlmaLinux support

multi-node/config/wazuh_cluster/wazuh_manager.conf, multi-node/config/wazuh_cluster/wazuh_worker.conf, single-node/config/wazuh_cluster/wazuh_manager.conf
This PR adds SUSE to the vulnerability detector configuration.
Closes https://github.com/wazuh/wazuh-docker/issues/926
=> Update the vulnerability detector default configuration block with missing providers

multi-node/config/wazuh_cluster/wazuh_manager.conf, multi-node/config/wazuh_cluster/wazuh_worker.conf, single-node/config/wazuh_cluster/wazuh_manager.conf
|Related issue|
|---|
|wazuh/wazuh#18516|
This PR adds the corresponding Debian Bookworm entry in the vulnerability detector default configuration after the changes in [Add support for Debian Bookworm in Vulnerability Detector](https://github.com/wazuh/wazuh/pull/18516)
=> Add Debian Bookworm to VDT default configuration

multi-node/docker-compose.yml, single-node/docker-compose.yml
Closes: https://github.com/wazuh/wazuh-docker/issues/951
The aim of this PR is to modify the `docker-compose.yml` files of the `single-node` and `multi-node` deployments in order to preserve the Wazuh dashboard configuration.
=> Fixed Wazuh dashboard modules persistency

CHANGELOG.md, README.md, multi-node/docker-compose.yml, single-node/docker-compose.yml
This PR is related to: https://github.com/wazuh/wazuh-docker/issues/981
=> Merge `4.5.3` into `4.6.0`

build-docker-images/wazuh-dashboard/Dockerfile, multi-node/docker-compose.yml, single-node/docker-compose.yml
This PR adds custom directory with specific permissions, and adds a Docker volume 
Issue Related https://github.com/wazuh/wazuh-docker/issues/990
=> Persist the custom logo in the Wazuh dashboard

build-docker-images/wazuh-indexer/config/config.sh, build-docker-images/wazuh-indexer/config/entrypoint.sh
closes https://github.com/wazuh/wazuh-docker/issues/1017
This PR aims to level file permissions between the per-package and per-docker installation of Wazun indexer, leaving the same permissions on the files.
The configuration path of the security policies is also corrected
<details>
<summary>Build images</summary>
```console
[root@centos7-1 ~]# git clone https://github.com/wazuh/wazuh-docker.git -b bug/1017-warning-opensearchsecurityplugin-wazuh-indexer-has-insecure-file-permissions-should-be-0600-to4.6.0
Cloning into 'wazuh-docker'...
remote: Enumerating objects: 11321, done.
remote: Counting objects: 100% (1360/1360), done.
remote: Compressing objects: 100% (685/685), done.
remote: Total 11321 (delta 731), reused 1206 (delta 603), pack-reused 9961
Receiving objects: 100% (11321/11321), …
```
=> Updated file permissions to have the same permissions as in package installation in Wazuh indexer

build-docker-images/build-images.sh
closes https://github.com/wazuh/wazuh-docker/issues/1016
tests:
<details>
<summary>build-docker-images/build-images.sh -v 4.6.0</summary>
```console
cbordon@cbordon-MS-7C88:~/Documents/wazuh/repositorios/wazuh-docker$ build-docker-images/build-images.sh -v 4.6.0
+ WAZUH_IMAGE_VERSION=4.6.0
+ WAZUH_TAG_REVISION=1
+ WAZUH_DEV_STAGE=
+ FILEBEAT_MODULE_VERSION=0.2
+ trap ctrl_c INT
+ main -v 4.6.0
+ '[' -n -v ']'
+ case "${1}" in
+ '[' -n 4.6.0 ']'
+ WAZUH_IMAGE_VERSION=4.6.0
+ shift 2
+ '[' -n '' ']'
+ build
++ echo 4.6.0
++ sed -e 's/\.//g'
+ WAZUH_VERSION=460
+ FILEBEAT_TEMPLATE_BRANCH=4.6.0
+ WAZUH_FILEBEAT_MODULE=wazuh-filebeat-0.2.tar.gz
+ WAZUH_UI_REVISION=1
+ '[' '' ']'
+ curl --output /dev/null --silent --head --fail https://github.com/wazuh/wazuh/tree/v4.6.0
+ curl --output …
```
=> Changed validation order for wazuh branch

build-docker-images/README.md, build-docker-images/build-images.sh, build-docker-images/wazuh-manager/Dockerfile
closes https://github.com/wazuh/wazuh-docker/issues/1116
Updated Filebeat module version to 0.3
```console
Processing triggers for libc-bin (2.31-0ubuntu9.12) ...
Processing triggers for ca-certificates (20230311ubuntu0.20.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container fb8678ed3bcb
---> 83505aaba314
Step 10/26 : COPY config/check_repository.sh /
---> 59ac71aa6efd
Step 11/26 : RUN chmod 775 /check_repository.sh
---> Running in 51afb04d5753
Removing intermediate container 51afb04d5753
---> 7e2b41d57b2d
Step 12/26 : RUN source /check_repository.sh
---> Running in 7db77ff41579
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: …
```
=> Updated Filebeat module version to 0.3

build-docker-images/wazuh-dashboard/config/install_wazuh_app.sh
Closes: https://github.com/wazuh/wazuh-docker/issues/1099
The aim of this PR is to adapt the Docker build to multiple Wazuh Dashboard plugins. This PR is related to https://github.com/wazuh/internal-devel-requests/issues/464.
The Wazuh stack was successfully deployed:
<details><summary>Show log</summary>
```console
$ build-docker-images/build-images.sh
Building wazuh.manager
Step 1/27 : FROM ubuntu:jammy
---> e4c58958181a
Step 2/27 : RUN rm /bin/sh && ln -s /bin/bash /bin/sh
---> Running in 15b77971c8d2
Removing intermediate container 15b77971c8d2
---> 68ebf2afdd3b
Step 3/27 : ARG WAZUH_VERSION
---> Running in a23005cb32f1
Removing intermediate container a23005cb32f1
---> b47401da587d
Step 4/27 : ARG WAZUH_TAG_REVISION
---> Running in 991b3313b34b
Removing intermediate container …
```
=> Adapted docker build to multiple Wazuh Dashboards plugins

build-docker-images/wazuh-dashboard/Dockerfile
Related https://github.com/wazuh/internal-devel-requests/issues/492
<details>
<summary>Docker images build</summary>
```console
Building wazuh.dashboard
Sending build context to Docker daemon  25.09kB
Step 1/38 : FROM ubuntu:focal AS builder
---> bf40b7bc7a11
Step 2/38 : ARG WAZUH_VERSION
---> Running in 328259785ee8
Removing intermediate container 328259785ee8
---> 6eee2e0c0467
Step 3/38 : ARG WAZUH_TAG_REVISION
---> Running in a952c5cd30c9
Removing intermediate container a952c5cd30c9
---> 216994b3819f
Step 4/38 : ARG INSTALL_DIR=/usr/share/wazuh-dashboard
---> Running in ab86a8b3cf87
Removing intermediate container ab86a8b3cf87
---> 8ab67c218a82
Step 5/38 : ARG WAZUH_UI_REVISION
---> Running in 510a99e3c61e
Removing intermediate container 510a99e3c61e
---> df2dcddbaf0d
Step 6/38 : RUN …
```
=> Removed report dependencies from Wazuh dashboard image

build-docker-images/README.md, build-docker-images/build-images.sh, build-docker-images/wazuh-dashboard/Dockerfile
Related: https://github.com/wazuh/wazuh-docker/issues/1130
The aim of this PR is to bump the 4.7.0 branch into the 4.7.1 branch.
=> Merge 4.7.0 into 4.7.1

build-docker-images/README.md, build-docker-images/build-images.sh, build-docker-images/wazuh-dashboard/Dockerfile, build-docker-images/wazuh-manager/Dockerfile, build-docker-images/wazuh-manager/config/filebeat_module.sh
Related: https://github.com/wazuh/wazuh-docker/issues/1133
The aim of this PR is to bump the changes of the 4.8.0 branch to the 4.8.1 branch
=> Merge 4.8.0 into 4.8.1

CHANGELOG.md, README.md
https://github.com/wazuh/wazuh-docker/issues/1156
The aim of this PR is to bump the changes of the 4.7.2 branch to the 4.8.0 branch
=> Merge 4.7.2 into 4.8.0

.github/workflows/push.yml, build-docker-images/wazuh-indexer/config/ism-check.sh, build-docker-images/wazuh-manager/config/filebeat.yml
https://github.com/wazuh/wazuh-docker/issues/1183
The aim of this PR is to bump the changes of the 4.8.1 branch to the 4.8.2 branch
=> Merge 4.8.1 into 4.8.2

build-docker-images/wazuh-manager/Dockerfile
This PR adds `xz-utils` package install into Wazuh manager Dockerfile.
Issue related https://github.com/wazuh/internal-devel-requests/issues/666
=> Add xz-utils install

build-docker-images/wazuh-manager/Dockerfile
This PR merge steps into Wazuh manager's Dockerfile for merge layers and build a smaller image.
Issue related https://github.com/wazuh/wazuh-docker/issues/1198
=> Merge layers into Wazuh manager Dockerfile

.github/.goss.yaml, build-docker-images/wazuh-dashboard/Dockerfile, build-docker-images/wazuh-dashboard/config/dl_base.sh, build-docker-images/wazuh-dashboard/config/install_wazuh_app.sh, build-docker-images/wazuh-indexer/Dockerfile, build-docker-images/wazuh-indexer/config/config.sh, build-docker-images/wazuh-manager/Dockerfile, build-docker-images/wazuh-manager/config/filebeat_module.sh
This PR fixes Wazuh manager Dockerfile because the execution order made issues when the container was deployed in Kubernetes.
Added correction to some warning messages for certain characters used with the grep command, which in the version containing the new base image generated warnings.
The version of the base image was also updated.
Related issue https://github.com/wazuh/wazuh-kubernetes/issues/596
=> Modify Dockerfile for Pod restart in Kubernetes

build-docker-images/wazuh-dashboard/config/config.sh, build-docker-images/wazuh-indexer/config/config.sh, indexer-certs-creator/config/entrypoint.sh
Related: https://github.com/wazuh/wazuh-docker/issues/1193
The aim of this PR is to fix some `4.8` references in the `4.9.0` branch. These changes were not considered in the bump of the `4.9.0` new version.
=> Fixed references to 4.8 version

build-docker-images/wazuh-indexer/config/entrypoint.sh
Removed securityadmin execution on wazuh-docker/build-docker-images/wazuh-indexer/config/entrypoint.sh
Closes https://github.com/wazuh/wazuh-docker/issues/1291#issue-2231921180
Build check fails because there are still no packages of 5.0.0 version. It's expected to fail on that check.
=> securityadmin commented lines in Wazuh indexer entrypoint removed

build-docker-images/wazuh-dashboard/Dockerfile, build-docker-images/wazuh-indexer/Dockerfile, build-docker-images/wazuh-manager/Dockerfile
Related issue: #1293 
Changed Docker base image from `amazonlinux:2023.3.20240304.0` to `amazonlinux:2023` as this change fixes the following known vulnerabilities:
| Vulnerability | Package |
|-----------|-----------|
| ALAS-2024-573 | python3-rpm |
| ALAS-2024-581 | libcurl-minimal |
| ALAS-2024-576 | expat |
Following, the manager, indexer and dashboard images have been built without issues.
Finally, they deployment was made and it was validated that it did without any issue.
I have also run the grype vulnerability scanner on this image and this is the result:
```
grype amazonlinux:2023 -o table
✔ Vulnerability DB                [updated]
✔ Pulled image
✔ Loaded image                                                        amazonlinux:2023.4.20240401.1
✔ Parsed image …
```
=> Fix 4.8.0 beta-5 AL2023 Vulnerabilities

multi-node/docker-compose.yml, single-node/docker-compose.yml
=> Changed image tag for 4.9.0 Alpha3

build-docker-images/wazuh-dashboard/Dockerfile, build-docker-images/wazuh-dashboard/config/wazuh.yml
This PR fixes the error deploying Wazuh stack in Kubernetes, because the `wazuh.yml` file not found before the first start of the Wazuh dashbaord service.
Related Issue https://github.com/wazuh/wazuh-kubernetes/issues/758
=> Add eazuh.yml file in the Wazuh dashboard image build process

.github/workflows/Procedure_push_docker_images.yml
This PR adds the initial workflow file for the `Procedure_push_docker_images` new GHA Workflow
Related issue: https://github.com/wazuh/wazuh-qa/issues/5651
=> Add the push_docker_images procedure workflow file

build-docker-images/wazuh-manager/config/etc/cont-init.d/2-manager
This PR revert issue https://github.com/wazuh/internal-devel-requests/issues/513 because the` create_user.py ` script is needed when the Wazuh manager container is restarted.
=> Revert create_user.py script deletion

multi-node/docker-compose.yml, single-node/docker-compose.yml
Related: https://github.com/wazuh/wazuh-docker/issues/1547
Revert Wazuh docker image to 4.9.1 version
=> Revert Wazuh images to 4.9.1 version

multi-node/docker-compose.yml, single-node/docker-compose.yml
This PR merges a revert of image tag versions. Reverted back to 4.10.0
More information can be found in the related issue: https://github.com/wazuh/wazuh-docker/issues/1570
=> Revert image tag to 4.10.0

CHANGELOG.md, build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init, build-docker-images/wazuh-manager/config/permanent_data.sh
This PR fixes the permanent data process between image files and entrypoint script.
Related issue https://github.com/wazuh/wazuh-docker/issues/1601
=> Fix permanent data scripts

CHANGELOG.md, build-docker-images/wazuh-dashboard/Dockerfile
This PR adds unset capabilities into `NodeJS` binaries.
Related issue https://github.com/wazuh/wazuh-docker/issues/1618
=> Add unset capabilities

CHANGELOG.md, build-docker-images/wazuh-dashboard/Dockerfile
=> Merge 4.10.1 into 4.10.2

.github/workflows/Procedure_push_docker_images.yml, .github/workflows/push.yml, .github/workflows/trivy-dashboard.yml, .github/workflows/trivy-indexer.yml, .github/workflows/trivy-manager.yml
This PR changes Ubuntu version in all workflows into the repository.
Closes https://github.com/wazuh/wazuh-docker/issues/1644
=> Change Ubuntu version used in workflows

.github/workflows/Procedure_push_docker_images.yml, CHANGELOG.md
The changes included in this PR aim to remove the default values of variables referencing the Wazuh-docker repository.
- https://github.com/wazuh/internal-devel-requests/issues/2137
=> Remove default docker reference version from workflow

CHANGELOG.md, multi-node/config/wazuh_cluster/wazuh_manager.conf, multi-node/config/wazuh_cluster/wazuh_worker.conf, single-node/config/wazuh_cluster/wazuh_manager.conf
This PR aims to add the new lists to the` ossec.conf` section on both the manager of the single-node setup and the master and worker nodes of the multi-node setup.
An environment with both single-node and multi-node deployments was deployed and tested. You can see the ossec.log in this comment:
- https://github.com/wazuh/wazuh-docker/issues/1869#issuecomment-2955436272
=> Add missing `malicious-ioc` ruleset lists

CHANGELOG.md, build-docker-images/wazuh-manager/config/permanent_data.env
When upgrading between different Wazuh images, the `/etc/filebeat/` path was included in the list of permanent data, so the file `/etc/filebeat/filebeat.yml` was never updated.
This PR changes that behavior by adding this file to the `PERMANENT_DATA_EXCP` list so that when upgrading to a new version, the file is updated as well.
You can see how the upgrade from one version to another was tested with these changes in this comment:
- https://github.com/wazuh/wazuh-docker/issues/1563#issuecomment-2991037102
=> Add filebeat config file in the `PERMANENT_DATA_EXCP` list

CHANGELOG.md, build-docker-images/wazuh-indexer/Dockerfile
- https://github.com/wazuh/wazuh-docker/issues/1924
- https://github.com/wazuh/wazuh-docker/issues/1924#issuecomment-3050214739
=> Update Dockerfile to copy `opensearch-security` files
